-- Drop table
DROP TABLE IF EXISTS preliminary;

-- Create preliminary table
CREATE TABLE preliminary (
    as_of_year INTEGER,
    respondent_id TEXT,
    agency_name TEXT,
    agency_abbr TEXT,
    agency_code INTEGER,
    loan_type_name TEXT,
    loan_type INTEGER,
    property_type_name TEXT,
    property_type INTEGER,
    loan_purpose_name TEXT,
    loan_purpose INTEGER,
    owner_occupancy_name TEXT,
    owner_occupancy INTEGER,
    loan_amount_000s INTEGER,
    preapproval_name TEXT,
    preapproval INTEGER,
    action_taken_name TEXT,
    action_taken INTEGER,
    msamd_name TEXT,
    msamd TEXT,
    state_name TEXT,
    state_abbr TEXT,
    state_code INTEGER,
    county_name TEXT,
    county_code TEXT,
    census_tract_number NUMERIC(10, 2),
    applicant_ethnicity_name TEXT,
    applicant_ethnicity INTEGER,
    co_applicant_ethnicity_name TEXT,
    co_applicant_ethnicity INTEGER,
    applicant_race_name_1 TEXT,
    applicant_race_1 INTEGER,
    applicant_race_name_2 TEXT,
    applicant_race_2 INTEGER,
    applicant_race_name_3 TEXT,
    applicant_race_3 INTEGER,
    applicant_race_name_4 TEXT,
    applicant_race_4 INTEGER,
    applicant_race_name_5 TEXT,
    applicant_race_5 INTEGER,
    co_applicant_race_name_1 TEXT,
    co_applicant_race_1 INTEGER,
    co_applicant_race_name_2 TEXT,
    co_applicant_race_2 INTEGER,
    co_applicant_race_name_3 TEXT,
    co_applicant_race_3 INTEGER,
    co_applicant_race_name_4 TEXT,
    co_applicant_race_4 INTEGER,
    co_applicant_race_name_5 TEXT,
    co_applicant_race_5 INTEGER,
    applicant_sex_name TEXT,
    applicant_sex INTEGER,
    co_applicant_sex_name TEXT,
    co_applicant_sex INTEGER,
    applicant_income_000s INTEGER,
    purchaser_type_name TEXT,
    purchaser_type INTEGER,
    denial_reason_name_1 TEXT,
    denial_reason_1 INTEGER,
    denial_reason_name_2 TEXT,
    denial_reason_2 INTEGER,
    denial_reason_name_3 TEXT,
    denial_reason_3 INTEGER,
    rate_spread NUMERIC(10,5),
    hoepa_status_name TEXT,
    hoepa_status INTEGER,
    lien_status_name TEXT,
    lien_status INTEGER,
    edit_status_name TEXT,
    edit_status INTEGER,
    sequence_number INTEGER,
    population_number INTEGER,
    minority_population NUMERIC(10,5),
    hud_median_family_income INTEGER,
    tract_to_msamd_income NUMERIC (10,5),
    number_of_owner_occupied_units INTEGER,
    number_of_1_to_4_family_units INTEGER,
    application_date_indicator INTEGER
);

-- Read CSV file into the preliminary table
\COPY preliminary FROM 'C:\Users\neuge\Documents\Rutgers University\Fall 2024\Principles of Information and Data Management\Projects\Project Data\hmda_2017_nj_all-records_labels.csv' WITH (DELIMITER ',', FORMAT CSV, HEADER, FORCE_NULL(as_of_year,respondent_id,agency_name,agency_abbr,agency_code,loan_type_name,loan_type,property_type_name,property_type,loan_purpose_name,loan_purpose,owner_occupancy_name,owner_occupancy,loan_amount_000s,preapproval_name,preapproval,action_taken_name,action_taken,msamd_name,msamd,state_name,state_abbr,state_code,county_name,county_code,census_tract_number,applicant_ethnicity_name,applicant_ethnicity,co_applicant_ethnicity_name,co_applicant_ethnicity,applicant_race_name_1,applicant_race_1,applicant_race_name_2,applicant_race_2,applicant_race_name_3,applicant_race_3,applicant_race_name_4,applicant_race_4,applicant_race_name_5,applicant_race_5,co_applicant_race_name_1,co_applicant_race_1,co_applicant_race_name_2,co_applicant_race_2,co_applicant_race_name_3,co_applicant_race_3,co_applicant_race_name_4,co_applicant_race_4,co_applicant_race_name_5,co_applicant_race_5,applicant_sex_name,applicant_sex,co_applicant_sex_name,co_applicant_sex,applicant_income_000s,purchaser_type_name,purchaser_type,denial_reason_name_1,denial_reason_1,denial_reason_name_2,denial_reason_2,denial_reason_name_3,denial_reason_3,rate_spread,hoepa_status_name,hoepa_status,lien_status_name,lien_status,edit_status_name,edit_status,sequence_number,population_number,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units,application_date_indicator));

-- Add applicant_id into the preliminary table
ALTER TABLE preliminary
ADD COLUMN applicant_id SERIAL;